### ISSUE TITLE
feature: update dart_define.gen.dart option

### ISSUE THREAD

**Issue by keima** [Mankeli-Software/dart_define#5]
### Description

I therefore request the addition of the `dart_define update` subcommand.
This is a subcommand whose sole purpose is to generate `dart_define.gen.dart` from the contents of the `dart_define:` section of `pubspec.yaml`.

### Motivation

This library is a very attractive tool in that it complements the official dart-define.

By the way, I think the only time this tool generates `dart_define.gen.dart` is when you do `dart_define generate`.
That's fine the first time, but as you continue to develop, environment variables may be added or removed.

In the current `dart_define generate`, there is no option to take an existing `dart_define.json` as an argument (something like `--dart-define-from-file` that can be used for input).
Therefore, using `dart_define generate --no-json` to update the dart file is also somewhat difficult,
In the end, you have to use the following command: `dart_define generate --no-json
`dart_define generate --no-json --KEY1=key1 --FLAVOR=dev`.

Maybe just allowing `dart_define generate` to read json files will work.
But what I'm looking for at the moment is an update to `dart_define.gen.dart`, so I'd be happy to see this feature implemented.

**Comment by O-Hannonen** [comment]
Hi Kouta! Thanks for the attraction to the tool and the feature request. 

So the issue is that `dart_define generate` does not take the existing `.json` config file into consideration, right? Therefore when you add a new config variable, it overrides the existing ones (in the `.json`) with default values from `.yaml` or the values provided as CLI options. I can definitely see why this is an issue.

**Comment by O-Hannonen** [comment]
The tool needs a value for each variable from yaml, system environment or CLI option. This is simply because it detects the variable type from the given "default" value.

Knowing this, I would propose the following changes to `dart_define generate` command:
1. If none of the above sources provide a default value, check if the config file already exists and has the value. If the value exists, read the variable type from there. Only if it is not provided in the above ways nor the config file will the command end up failing.
2. Add a `--force` flag. If someone wants to override a value that already exists in config file. This would also be necessary to use CI/CD pipelines if the pipeline caches the codebase (does not always start from fresh clone).

With these changes you could simply run `dart_define generate` after adding new variables to the config yaml file. Would this meet your needs @keima?

**Comment by keima** [comment]
@O-Hannonen 
Thanks for your positive consideration!
I consider the proposed modifications to meet my needs.

To add to point no.1, it would be appreciated if you could refer to the `--json_path` option, not just the `dart_define: json_path` in `pubspec.yaml`.
I would be happy if the following command could be executed when the `variables:` option is changed, so that `dart_define.gen.dart` is updated.
`dart_define generate --no-json --json_path=. /env.dev.json --FLAVOR=dev`.

**Comment by O-Hannonen** [comment]
Hi @keima!

Just released a new version with the fixes described above. Thanks for your contribution to making this tool better!

**Comment by keima** [comment]
@O-Hannonen 
Thanks for implementing this!
I updated this library to ensure that it is being handled as it should be.

Good job!
